spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1020700319099-mfir2ln2t5255mp5ja5fh0u3d0ajhp0c.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot