INSERT INTO ARTICLE (TITLE, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT) VALUES ('제목 2', '내용 2', 'user1', NOW(), NOW())
INSERT INTO ARTICLE (TITLE, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT) VALUES ('제목 3', '내용 3', 'user2', NOW(), NOW())
INSERT INTO ARTICLE (TITLE, CONTENT, AUTHOR, CREATED_AT, UPDATED_AT) VALUES ('제목 1', '내용 1', 'user3', NOW(), NOW())
